// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.45.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'gened_ucci_api.dart';
export 'gened_ucci_api.dart';
import 'package:meta/meta.dart';
import 'dart:ffi' as ffi;

class UcciApiPlatform extends FlutterRustBridgeBase<UcciApiWire> {
  UcciApiPlatform(ffi.DynamicLibrary dylib) : super(UcciApiWire(dylib));
// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_opt_String(String? raw) {
    return raw == null ? ffi.nullptr : api2wire_String(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_1(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: api_fill_to_wire

}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class UcciApiWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  UcciApiWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  UcciApiWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire_subscribe_ucci_engine(
    int port_,
    int player,
    ffi.Pointer<wire_uint_8_list> engine_path,
  ) {
    return _wire_subscribe_ucci_engine(
      port_,
      player,
      engine_path,
    );
  }

  late final _wire_subscribe_ucci_enginePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Int32,
              ffi.Pointer<wire_uint_8_list>)>>('wire_subscribe_ucci_engine');
  late final _wire_subscribe_ucci_engine = _wire_subscribe_ucci_enginePtr
      .asFunction<void Function(int, int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_write_to_process(
    int port_,
    ffi.Pointer<wire_uint_8_list> command,
    int msec,
    int player,
    ffi.Pointer<wire_uint_8_list> check_str_option,
  ) {
    return _wire_write_to_process(
      port_,
      command,
      msec,
      player,
      check_str_option,
    );
  }

  late final _wire_write_to_processPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Uint32,
              ffi.Int32,
              ffi.Pointer<wire_uint_8_list>)>>('wire_write_to_process');
  late final _wire_write_to_process = _wire_write_to_processPtr.asFunction<
      void Function(int, ffi.Pointer<wire_uint_8_list>, int, int,
          ffi.Pointer<wire_uint_8_list>)>();

  void wire_is_process_loaded(
    int port_,
    int msec,
    int player,
  ) {
    return _wire_is_process_loaded(
      port_,
      msec,
      player,
    );
  }

  late final _wire_is_process_loadedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Uint32, ffi.Int32)>>('wire_is_process_loaded');
  late final _wire_is_process_loaded =
      _wire_is_process_loadedPtr.asFunction<void Function(int, int, int)>();

  void wire_is_process_unloaded(
    int port_,
    int msec,
    int player,
  ) {
    return _wire_is_process_unloaded(
      port_,
      msec,
      player,
    );
  }

  late final _wire_is_process_unloadedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Uint32, ffi.Int32)>>('wire_is_process_unloaded');
  late final _wire_is_process_unloaded =
      _wire_is_process_unloadedPtr.asFunction<void Function(int, int, int)>();

  void wire_get_engine_name(
    int port_,
    int player,
  ) {
    return _wire_get_engine_name(
      port_,
      player,
    );
  }

  late final _wire_get_engine_namePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'wire_get_engine_name');
  late final _wire_get_engine_name =
      _wire_get_engine_namePtr.asFunction<void Function(int, int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_1(
    int len,
  ) {
    return _new_uint_8_list_1(
      len,
    );
  }

  late final _new_uint_8_list_1Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_1');
  late final _new_uint_8_list_1 = _new_uint_8_list_1Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
